### ISSUE TITLE
프로젝트 주제 별 참조 자료 링크

### ISSUE THREAD

**Issue by protocol5** [protocol5/2021ESE-Mooyaho_team#2]
## 해당 이슈는 주제 또는 개발 파트 별 참조 자료 공유를 목적으로 하는 저장 공간입니다.

- [x] 다음과 같은 간단한 양식이 존재합니다. **양식을 준수하여 제출하여 주세요.**

> 주제 또는 개발 파트 명(간단하게 서술) : 참조 자료 링크 목적, 자료 링크(하이퍼 링크 권장),참조 파일 번호, @멘션

- 드래그앤 드롭으로 파일을 올릴 수 있습니다. 참조 파일 업로드시 캡션 번호 입력 부탁드립니다.
- 자료에는 동영상, 이미지, 텍스트, 논문 어떤것도 가능합니다.
- 기존에 작성했던 코멘트라면 edit을 통해 추가해주세요.(깔끔한 관리를 위한 권장)
- 코멘트는 삭제하지 말아주세요. 
- 멘션 기능을 통해 관련 이슈자를 선택해주시면 좋습니다.(권장)
- 자세한 예시는 아래 답글을 확인해 주세요.

@DongJune96 @ckdrkt2 @han45699

**Comment by protocol5** [comment]
스마트 미러를 활용한 수화: 손가락 및 손 인식, [유튜브](https://www.youtube.com/watch?v=KtfhmpNvY7Y)

**Comment by protocol5** [comment]
이미지 인식 관련 주제 : 인식 프레임 증가하는 방법, resize 함수를 통해 이미지 크기를 줄여 로드 시간을 줄인다.

**Comment by DongJune96** [comment]
.

**Comment by han45699** [comment]
> 이미지 인식 관련 주제 : 인식 프레임 증가하는 방법, resize 함수를 통해 이미지 크기를 줄여 로드 시간을 줄인다.
> rgb color scale에서 grayscale로 변환후에 이미지 연산을 하면 속도가 빠르다. (추가시킴 한관우)

댓글

**Comment by han45699** [comment]
# 개인적으로 생각해본 주제
> 객체 인식 알고리즘 + 라이다를 이용한 전동킥보드 제동장치 및 경고음 장치

- 카메라로 영상 데이터 받아서 객체 인식 알고리즘을 통해 앞에 있는 객체 인식
- 추가적인 이미지 처리를 통해 물체와의 거리 계산
- 거리가 임의로 지정한 threshold보다 가까우면 경고음 출력 및 제동장치 작동
- 이미지 처리 뿐만 아니라 라이다 데이터를 최후의 안전 수단으로 사용

**Comment by DongJune96** [comment]
라즈베리파이 프로젝트 참조 사이트
https://www.hackster.io/raspberry-pi/projects
https://nevonprojects.com/raspberry-pi-projects/
https://pimylifeup.com/category/projects/

**Comment by DongJune96** [comment]
## 의식의 흐름

라즈베리파이에 무게, 바코드 센서를 장착해 카트에 물건을 넣으면 자동 계산
 ==> 벌써 생각보다 많이 발전된듯 이마트에서 사람 따라다니는 자율주행 카트 시연영상도있음
 아마존에서도 개발중인듯

**Comment by han45699** [comment]
## 아마존 Alexa와 라즈베리 파이를 이용한 노크한 사람 인지 + 문 개폐, 사람데이터 저장 상호작용

https://www.hackster.io/gmelaub/alexa-who-s-at-the-door-d0f6b5#

-알고리즘
1. 누가 노크를 하면, 집 안에 있는 사람이 알렉사를 부른다.
2. 문 앞에 누가 있어? 하고 물어보면 알렉사가 사진을 찍고 이미지 처리를 통해 누구인지 인식한다.
3. 만약 아는 사람이면 그 사람 이름을 알려준다.
4. 만약 모르는 사람이면 사진을 찍을까요? 하고 물어본다. 이후 사용자가 이름 데이터를 말해주면 그 이름으로 새로운 사람을 저장한다.
5. 데이터를 쌓으면 쌓을 수록 인지 정확도가 상승한다.

- 추가하고 싶은 아이디어
라즈베리 파이가 문에 부착되어있게 만든 다음, 노크가 울리면 자동적으로 집 안에 있는 사람에게 (아는 사람이면 '홍길동'이 노크했습니다.) 또는 (모르는 사람이면 '모르는 사람'이 노크를 했습니다.) 하고 알려주기

상호작용 하는 과정에서 사용자가 통화하고 싶다고 말하면 모니터에 캠 띄우고 음성 통화 가능하게 하기

**Comment by han45699** [comment]
## 도어벨 누르면 집안의 사용자 스마트폰에 이메일이 가서, 이메일에 접속하면 서로 영상통화가 되게 하는 프로젝트

https://www.hackster.io/hackershack/smart-doorbell-video-intercom-system-e5aa61

**Comment by ckdrkt2** [comment]
# 가위 바위 보 로봇
![ezgif com-gif-maker](https://user-images.githubusercontent.com/72551588/110811534-22931000-82ca-11eb-8f53-4bf77af6580d.gif)
[https://projects.raspberrypi.org/en/projects/rock-paper-scissors-by-hand](url)

- 카메라로 손의 모양을 인식하여 가위 바위 보 게임을 진행하는 로봇
- 아쉽게도 코드를 제공하는 것 같지는 않고 Techable Machine 이라는 사이트를 통해서 서비스 제공
- 손 또는 손가락 인식 주제(수화 등)에 응용하거나 적용할 수 있는 방법을 찾으면 도움이 될 거라고 생각
- 같은 사이트 내에 있는 이미지 인식 관련 내용 링크
[https://projects.raspberrypi.org/en/projects/amazing-image-identifier](url)

**Comment by ckdrkt2** [comment]
# 라즈베리파이4로 토이프로젝트용 서버 만들기
[https://ryan-han.com/post/server/raspberry_server_1/](url)

- 라즈베리 파이 4와 추가적으로 필요한 제품(쿨링 팬 등)을 사용하여 간단한 서버 구축
- IoT과 같은 주제를 사용하게 되었을 때 활용할 수 있을 것이라고 생각

**Comment by ckdrkt2** [comment]
# 라즈베리 파이 얼굴 인식 with Python, OpenCV, Deep learning
![제목 없음](https://user-images.githubusercontent.com/72551588/110804589-ab5a7d80-82c3-11eb-93e9-96c472703cf2.jpg)
[https://www.pyimagesearch.com/2018/06/25/raspberry-pi-face-recognition/](url)

- 인식 과정
![image](https://user-images.githubusercontent.com/72551588/110810017-bc59bd80-82c8-11eb-918e-ccda04b8609f.png)
- 라즈베리 파이로 얼굴 인식에 대한 가이드 제공
- 전체적인 과정과 코드 구조에 대해 설명이 되어있고 전체 코드도 다운받을 수 있음
- 소스 코드 외에도 17 페이지 정도 되는 가이드를 제공(이메일 작성 시)
- 이외에도 pyimagesearch에 라즈베리 파이 관련되어 사용할 수 있는 OpenCV에 대한 내용들이 있음
[https://www.pyimagesearch.com/?s=raspberry+pi+opencv](url)

**Comment by protocol5** [comment]
## 다중 무선 충전 패드 - 샤오미

- 여러 전자기기를 패드위에 올리면 기기의 좌표를 찾아 충전 단자가 찾아감
- 모든 제품의 충전을 지원
- 구성이 간단하여 구현 가능하나 만약 주제로 된다면 개선사항이 필요
- 단점으로는 모터 소음과 좌표를 찾아가는 시간
![image](https://user-images.githubusercontent.com/68097267/110817337-8c61e880-82cf-11eb-824c-a936c1b23676.png)
[유튜브 링크](https://www.youtube.com/watch?v=nqfbGxIaVgs)

**Comment by DongJune96** [comment]
## 시계

![image](https://user-images.githubusercontent.com/68097144/110819908-faa7aa80-82d1-11eb-96b4-736d26cf3a98.png)
![image](https://user-images.githubusercontent.com/68097144/110819951-02674f00-82d2-11eb-8528-94eef37d0eeb.png)

- 여러개의 작은 아날로그 시계들이 디지털 시계 처럼 동작

- 시간을 표시하는 것 뿐만 아니라 특정 문구나 그림 등 사용자가 원하는 것을 출력하도록 한다면 괜찮을듯 
- 
![image](https://user-images.githubusercontent.com/68097144/110820722-b49f1680-82d2-11eb-92d9-5f5ab3b955c0.png)
이런식으로 특정 시간마다 시간을 펜을 이용해 썼다 지웠다하는 비효율적인? 프로젝트도있음

**Comment by protocol5** [comment]
유태영 comment : 라즈베리파이사용시 fps낮게나옴, 젯슨보드를 tcp/ip로 붙여도 최대 30fps 밖에 안나옴.

**Comment by han45699** [comment]
No.1 | 적외선 센서를 이용한 비접촉 엘리베이터 스위치+얼굴인식 | 고동준 | 비고
-- | -- | -- | --
  | [요약] 코로나 시대에 비접촉을 위한 버튼 방식이 아닌 적외선 센서와 안면 인식을 이용한 엘리베이터 스위치 버튼 방식이 아닌 적외선 센서와 안면 인식을 이용한 엘리베이터 스위치 + 사용자의 높이에 따라 이동  [장점]  - 코로나로 인해 비접촉이 대두화되는 시기에 실제 물리적으로 누르는 버튼보다 안전하게 사용 가능  - 안면인식을 통해 기존의 카드키를 대면 해당 층으로 이동하는 것보다 개선가능  - 아이, 어른 등 다양한 사용자의 눈높이와 키높이에 맞춰 자동으로 레일을 이용해 자동으로 이동  [구동 알고리즘]   1. 사람이 엘리베이터에 탑승하면, 안면 인식 진행  2. 등록된 사용자이면 등록된 층으로 자동 이동  3. 등록되지 않은 사용자이면, 층수 입력  4. 아래의 사진과 같이  손가락으로 이동하고자하는 층을 입력  5. 적외선센서 또는 카메라를 이용해 손가락의 움직임으로 층수 판별 |   |

**Comment by protocol5** [comment]
웹캠 설정 https://webnautes.tistory.com/909

**Comment by ckdrkt2** [comment]
# 최종 주제 관련 조사

1. Finger Detection and Tracking using OpenCV and Python
![image](https://user-images.githubusercontent.com/72551588/111884452-106d4c00-8a05-11eb-9b05-e08b11d83b2a.png)
https://dev.to/amarlearning/finger-detection-and-tracking-using-opencv-and-python-586m

- 피부색과 히스토그램을 이용하여 손을 인식하고 마스킹으로 경계를 나눔
- 이미지 형상 분리는 cv2.calcBack Project 를 사용
- 손가락 끝 인식을 위해 마스킹 한 경계에 등고선을 그리고 등고선의 중심에서 가장 멀리 떨이진 볼록한 부분을 확인
- 볼록한 부분들을 결점으로 간주하고 가장 멀리 떨어져있는 결점을 손가락 끝으로 인식

2. Hand-Tracking For Smartphone AR Apps Is On Its Way
![KakaoTalk_20210320_155123539](https://user-images.githubusercontent.com/72551588/111885099-fd5c7b00-8a08-11eb-9d1f-031a855624bd.gif)
https://www.vrfocus.com/2018/06/hand-tracking-for-smartphone-ar-apps-is-on-its-way/

3. Ball Tracking with OpenCV
![image](https://user-images.githubusercontent.com/72551588/111884527-870a4980-8a05-11eb-97eb-ed15000bc5f5.png)
https://www.pyimagesearch.com/2015/09/14/ball-tracking-with-opencv/

4. Finding extreme points in contours with OpenCV
![image](https://user-images.githubusercontent.com/72551588/111884968-36482000-8a08-11eb-835b-bbb6fcfc11d2.png)
https://www.pyimagesearch.com/2016/04/11/finding-extreme-points-in-contours-with-opencv/

5. OpenCV People Counter
![opencv_people_counter_result01](https://user-images.githubusercontent.com/72551588/111885070-dc942580-8a08-11eb-9a20-49c10a72a8a1.gif)
https://www.pyimagesearch.com/2018/08/13/opencv-people-counter/

- 카메라로 사람의 입출입을 카운트하는 OpenCV
- 엘리베이터 또는 건물 보안과 관련되어 사용할 수 있을 것으로 생각되어서 추가함
